server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRealy
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-services
          uri: lb://users-services
          predicates:
            - Path=/user/**
          filters:
            -RemoveRequestHeader=Cookies
        - id: cars-services
          uri: lb://cars-services
          predicates:
            - Path=/car/**
          filter:
            - RemoveRequestHeader=Cookie
        - id: bikes-services
          uri: lb://bikes-services
          predicates:
            - Path=/bike/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/microservices-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8080/realms/microservices-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8080/realms/microservices-realm/protocol/openid-connect/token
          registration:
            microservices-client:
            provider: keycloak
            client-id: microservices-client
            client-secret: db71fcef-2ef1-43fb-8555-8697ec73109f
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/microservices-client"