server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRealy
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-services
          uri: lb://users-services
          predicates:
            - Path=/user/**
        - id: cars-services
          uri: lb://cars-services
          predicates:
            - Path=/car/**
          filter:
            - RemoveRequestHeader=Cookie
        - id: bikes-services
          uri: lb://bikes-services
          predicates:
            - Path=/bike/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/microservices/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8080/realms/microservices/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8080/realms/microservices/protocol/openid-connect/token
          registration:
            client-name:
            provider:
            client-id:
            client-secret:
            authorization-grant-type:
            redirect-uri: