server:
  port: 8081
Spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/Raulcudris/microservices-whit-springboot
          search-paths: config-data
  application:
    name: config-service
